apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-pv
  namespace: demo-storage
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /home/jbl/demo-storage/pgdata

