apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: {{ .Values.storage.hostPath | quote }}
